### PR TITLE
Add .terraform-version for tfenv

### PR DESCRIPTION
**Pull request by tptee**
Pinned to the latest 0.11.x

### CODE REVIEW

**Review by ryan-roemer — APPROVED** [review]
Can we also add CLI install instructions for at least mac to get this version?

like

```sh
$ brew install terraform@0.11.14
```

or something?

**Comment by tptee** [comment]
For Mac, you have to use `tfenv` in place of `brew` Terraform–they conflict and Homebrew gives a descriptive error. Should we assume `tfenv` for this project in the docs?

**Comment by ryan-roemer** [comment]
I don't mind what we use as long as it's CLI and can be described at least for Mac in `sh` command examples in https://github.com/FormidableLabs/aws-lambda-serverless-reference#terraform section

Totally up to you!

**Comment by tptee** [comment]
Cool! I'll update to use `tfenv` in the docs since we've been using it in CI/localdev in other projects!

**Comment by tptee** [comment]
Docs added! Merging

**Pull request merged**
