### PR TITLE
[WIP] Update node verison to 12.13.0

### LINKED ISSUE #32: SLS: update runtime to node12
Let's update our runtime!

- [x] Update serverless runtime to node 12 (or 10 if issues).

### PR DESCRIPTION
**Pull request by andyrichardson**
Fix #32

## Changes
 - Update target Node version in .nvmrc
 - Rebuild lockfiles using updated node version
 - Update target lambda environment 

## Notes
 - Deletions don't look to be working (or I've broken something) so cannot yet check if this works on a deployment

### CODE REVIEW

**Comment by ryan-roemer** [comment]
What is the specific delete command you are using?

**Comment by andyrichardson** [comment]
`tf:service:_delete`

Will try undeploying using SL but unsure if that will work now that tf stack is partially deleted.

**Comment by ryan-roemer** [comment]
Ah! For this exercise, we should not be using any `tf` commands. Only `sls` commands as `-admin|-developer`

(There's nothing that changed Terraform-wise, so we shouldn't be changing things)

**Comment by ryan-roemer** [comment]
E.g.,

```sh
$ STAGE=sandbox yarn run lambda:deploy
```

as `-developer` or `-admin` to test upgrade worked.

To test whole thing, then:

```sh
$ STAGE=sandbox yarn run lambda:_delete
$ STAGE=sandbox yarn run lambda:deploy
```

As an `-admin` user.

**Comment by andyrichardson** [comment]
Yeah I think I broke something

Weirdly enough, I'm getting token errors for any IAM request on the AWS CLI, I've checked the outgoing HTTP request and it looks correct.

[logs.txt](https://github.com/FormidableLabs/aws-lambda-serverless-reference/files/3905267/logs.txt)

**Comment by ryan-roemer** [comment]
Looking at the logs you're running all the CF + TF (should be superadmin only) and SLS (should be `-admin` or `-developer` only) as the same user `aws-vault exec root`.

I'm going to try and nuke everything and reset to `master` then we you can try again here as I outlined https://github.com/FormidableLabs/aws-lambda-serverless-reference/pull/33#issuecomment-559582372 with only your `-developer` and/or `-admin` users...

**Comment by ryan-roemer** [comment]
The CF bootstrap state is fine.

The TF state is messed up and we have extra VPCs and resources. I'm cleaning up manually.

**Comment by ryan-roemer** [comment]
I can't delete the VPC because two ENIs are stuck and won't let me (even as our most privileged account) delete them. I'm going to give a little time before trying again.

Please consider this PR blocked and unfortunately that means we're going to have to stop work on things until I can figure this out or it let's me delete the ENIs.

@tptee -- I've got a resource group of things to delete here? https://console.aws.amazon.com/resource-groups/group/simple-reference-sandbox?region=us-east-1

The ENI's I'm trying to detach are at https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#NIC:vpcId=vpc-0d8ae7b5888bdc0b1;status=in-use;sort=networkInterfaceId if you have a better idea of how to force detach them?

**Comment by ryan-roemer** [comment]
There weirdly seems like a mismatch of `prod` and `sandbox` Stage values. Like we have `sandbox` TF values depending on `prod` stage values. I have no idea how this could have happened except maybe by hard-coding `prod` into SLS stuff config wise while doing a CF/TF updates with `STAGE=prod`...

... at any rate, nuking everything `prod` or `sandbox` with fire in the console.

**Comment by andyrichardson** [comment]
That's really unusual - at the time I hadn't really touched any of the CF/tf stuff. 

I was convinced it was caused by destroying things in the wrong order. I'll grep through my bash history later and upload a log to work out how this happened

**Comment by ryan-roemer** [comment]
Update: have nuked existing stuff.

Recreating tf with:

```sh
$ STAGE=sandbox aws-vault exec <superadmin-user> -- yarn tf:service:apply
```

Hitting error:

```
14 errors occurred:
	* module.serverless_vpc.aws_iam_policy.developer: 1 error occurred:
	* aws_iam_policy.developer: Error creating IAM policy tf-simple-reference-sandbox-developer-vpc: InvalidClientTokenId: The security token included in the request is invalid
	status code: 403, request id: 2ba766b9-356d-41cb-bc8e-fe5445760c6e

... similar stuff ...
```

Looks like it might be something like: 

- https://github.com/99designs/aws-vault/issues/266
- https://github.com/99designs/aws-vault/issues/455

I'll research this more as I'm pretty sure I created with tf stack originally without `aws-vault`, so is potentially a legit issue to solve.

**Comment by andyrichardson** [comment]
This could be it - originally I was using local .env files but then moved to aws-vault (which is when issues eventually started to occur)

**Comment by ryan-roemer** [comment]
Honing IAM issue down to just pure aws (not using this project/tf at all):

```sh
$ STAGE=sandbox aws-vault exec <superadmin-user> -- aws iam list-roles 

An error occurred (InvalidClientTokenId) when calling the ListRoles operation: The security token included in the request is invalid
```

**Comment by andyrichardson** [comment]
Yup, seen that one before 👍

**Comment by andyrichardson** [comment]
So it looks like the issue is that 2FA/MFA is required to create a session as an IAM user where no additional IAM role is provided (i.e. run as all roles accessible to this account). This is likely a security measure to encourage scoping of both accounts and roles.

Won't be an issue when using `AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx aws iam list-roles` as this approach doesn't use sessions.

The quick fix is to add the `--no-session` flag when calling `aws-vault exec` which will simulate the above example. This should be fine as long as we have confidence in the commands being executed.

I think running commands through tensorflow (see #34) will help with this as it prevents us from granting unnecessary permissions to processes (example below).

Another (minor) security improvement we can make is by specifying the role using `AWS_ROLE_ARN=someRole` when executing commands. Automating this in TF should be easy.

## Example
**AccountA (permissions/roles)**
 - Create VPC
 - Deploy Lambda service
 - ...etc

### Good
`aws-exec --no-session exec AccountA -- yarn tf:tensorflow:apply`

Tensorflow process is granted
 ✅  Create VPC
 ✅  Deploy Lambda service

_all required permissions are satisfied and no unnecessary permissions are provided._

### Bad
`aws-exec --no-session exec AccountA -- yarn lambda:deploy`

Serverless process is granted
 ❌ Create VPC
 ✅  Deploy Lambda service

_additional unnecessary permissions are granted to the process._

**Comment by ryan-roemer** [comment]
@andyrichardson -- This PR is unblocked! 🎉 

From here, once this PR is in final shape, can you run a:

```sh
$ STAGE=sandbox aws-vault exec FIRST.LAST-developer --no-session -- \
  yarn lambda:deploy
```

(If that doesn't work for some reason, then try `FIRST.LAST-admin` instead)

And verify the deployed functions look good, then ping for final review!

**Comment by andyrichardson** [comment]
Closing in favour of #43

**Pull request closed without merging**
